### ISSUE TITLE
classSet() brings up a warning with React 0.14.5

### ISSUE THREAD

**Issue by erikajon** [react-component/switch#1]
I have this warning in my console when trying to render a `<Switch/>` component and (I assume because of this) the component does not render.

```
`rcUtil.classSet()` is deprecated, use `classNames()` by `require('classnames')` instead
```

If it's not going to break anything, I could create a PR that updates classSet() with className()?

**Comment by benjycui** [comment]
Try the latest version.

See: https://github.com/react-component/switch/blob/master/package.json#L3

**Comment by erikajon** [comment]
Awesome, thank you!!
