### ISSUE TITLE
More flexibility, less API? 

### ISSUE THREAD

**Issue by monkindey** [react-component/switch#16]
Before

```js
<Switch checkedChildren="开" unCheckedChildren="关" />
```

After

```js
<Switch>
  {
    (checked) => checked ? '开' : '关'
  }
</Switch>
```

And we just change the [#L89-L91](https://github.com/react-component/switch/blob/master/src/Switch.jsx#L89-L91) code to 

```js
<span className={`${prefixCls}-inner`}>
  {this.props.children(checked)}
</span>
```

But maybe we should backward compatibility.  😔

Inspired by [react-autocompletely](https://github.com/paypal/react-autocompletely)

Any idea ?

**Comment by afc163** [comment]
I like it, how about propose a PR for this?

**Comment by monkindey** [comment]
Is it a breaking change? or should be backward compatibility?

yes, It's pleasure to make a PR for this.

**Comment by afc163** [comment]
Right, it should be backward compatibility.

**Comment by paranoidjk** [comment]
-1 for this

```js
<Switch>
  {
    (checked) => checked ? '开' : '关'
  }
</Switch>
```

I am against to add complex logic in jsx.
`switch` only got two status, do we really need to use a function?

**Comment by monkindey** [comment]
Everyone has his own taste. Maybe you are right, but in my opinion, I love the flexibility, I don't want to remember the too many custom API, why not inversion of control to the user end, give the user more power? I have done it and are ready to make a PR, and saw the thumbs down 👎 below my issue, do you know what it feels like? I just discuss something with you guys, you must be clever than me, but I think my issue is not the spam or invalid.

Sorry for the bother.

More information https://github.com/paypal/react-autocompletely/pull/68

**Comment by paranoidjk** [comment]
@monkindey 😅 

Sorry, My bad... I will cancel the emoji vote.  

You seems to misunderstand about this action, actually we use thumbs up and thumbs down just to represent whether we agree with a proposal, such as https://github.com/ant-design/ant-design-mobile/issues/1217

Please aware that this emoji is just represent a vote, no more.

**Comment by monkindey** [comment]
Sorry about that, I misunderstood it. 

Thanks for your clarification. It make sense to me now. 😀

**Comment by benjycui** [comment]
But, could rc-switch support more use case after this change? I doubt it.

**Comment by monkindey** [comment]
🤔 Maybe, no. The main benefit is `Let's forget API, Keep it simple`.

**Comment by paranoidjk** [comment]
@monkindey

IMO, Boolean is more simple than function. Even we use function, i prefer props, not in jsx.

```jsx
const renderContent = checked => checked ? '开' : '关';

<Switch renderContent={renderContent}/>
```

**Comment by monkindey** [comment]
>  i prefer props, not in jsx

😀 renderContent, this also is a custom API. Because we want to render something into Switch, we can use the React's children. 

> Boolean is more simple than function

for example ?

**Comment by paranoidjk** [comment]
> Because we want to render something into Switch, we can use the React's children.

But your childern is a funtion which receive component inner state as param. 

You do `content = this.props.children(this.state.checked)`

I am not sure users will accept this idea easily.

**Comment by paranoidjk** [comment]
Normally, we think jsx should declarative, and `props.children` should be react nodes.

What you propose is to manipulate `props.children`, in some way, it's a trick.

**Comment by paranoidjk** [comment]
Please aware that below two way is totally different mental model.

```js
// checked is from inner, children is a function
<Switch>
  {
    (checked) => checked ? '开' : '关'
  }
</Switch>
```

```js
// checked is from outer, children is a react node
<Switch>
  {
    checked ? '开' : '关'
  }
</Switch>
```

**Comment by monkindey** [comment]
In React' s world, Everything is function, right?

```js
(checked) => checked ? '开' : '关'
```

this is a function component, isn't it ? 😉

A function component inside Switch Component and we give it a state like checked.

**Comment by monkindey** [comment]
Sorry about that, it's not function component, just similar to it

**Comment by paranoidjk** [comment]
But is counterintuitive (违反直觉的). Let me rewrite your demo in below way:

```jsx

const SwitchContent = (checked) => checked ? '开' : '关';

<Switch>
  <SwitchContent />
</Switch>
```

**Comment by paranoidjk** [comment]
Users may wonder where the `SwitchContent.props.checked` come from ?

**Comment by paranoidjk** [comment]
Let me sum up, my point is:

> What you propose is to manipulate props.children, in some way, it's a trick.

**Comment by monkindey** [comment]
yes, you're right, it's not a function component. 

I at dan, seb and kent on twitter. I don't know whether they notice it.

**Comment by yesmeck** [comment]
https://facebook.github.io/react/docs/jsx-in-depth.html#functions-as-children

**Comment by paranoidjk** [comment]
> This usage is not common, but it works if you want to stretch what JSX is capable of.

> I am not sure users will accept this idea easily.

**Comment by yesmeck** [comment]
<img width="646" alt="dingtalk20170802221328" src="https://user-images.githubusercontent.com/465125/28877747-dc945996-77cf-11e7-98f4-3ddda4d40983.png">

**Comment by yesmeck** [comment]
https://spectrum.chat/thread/61f5aa00-f00e-4d90-859f-f5ad921bfda6

**Comment by paranoidjk** [comment]
If the react team attempt to recommend this way, i am ok with it. I just want to make sure we do not make extra trouble for users, since `<Switch checkedChildren="开" unCheckedChildren="关" />` is extremely simple.

**Comment by benjycui** [comment]
> But, could rc-switch support more use cases after this change? I doubt it.

If the feature cannot make rc-switch support more use cases, this API is not more flexible, it just introduce a breaking change.

**Comment by monkindey** [comment]
It will be backward compatibility. That is, you have two ways to set the children

```js
<Switch checkedChildren="开" unCheckedChildren="关" />
```

and 


```js
<Switch>
  {
    (checked) => checked ? '开' : '关'
  }
</Switch>
```

**Comment by benjycui** [comment]
I still -1 for this, it is not worth doing so.

**Comment by monkindey** [comment]
OK, Thank you guys for discussing with me. It's interesting. 

I am going to close this issue because of most of your team disagree with it.
