### ISSUE TITLE
Switch form not rendering

### ISSUE THREAD

**Issue by FelixBrendel** [react-component/switch#18]
I don't know if I am not using it correctly, but just following the instructions my switch only looks like this:
![image](https://user-images.githubusercontent.com/5005975/30344870-498b6488-9803-11e7-9fc3-50c2827709b0.png)
The online demo worked well.
So only the text is rendered. However when I click it, it changes the state. I even included the same `.less` file as in the demo.
I am not very experiences with js or react. I Used the "create-react-app" to set up the boilerplate.
```jsx
import "./index.less"
import React from 'react';
import ReactDOM from 'react-dom';
import Switch from 'rc-switch';

function onChange(value) {
  console.log(`switch checked: ${value}`); // eslint-disable-line
}

class App extends React.Component {

    state = {
      disabled: false,
    }

    toggle = () => {
      this.setState({
        disabled: !this.state.disabled,
      });
    }

    render() {
        return (
            <Switch
              onChange={onChange}
              disabled={this.state.disabled}
              checkedChildren={'开'}
              unCheckedChildren={'关'}
            />
        )
    }
}

export default App;
```

**Comment by benjycui** [comment]
A re-producible repo is better.

**Comment by benjycui** [comment]
Close for no response.
