### ISSUE TITLE
Switch styles

### ISSUE THREAD

**Issue by JikkuJose** [react-component/switch#19]
Think providing the CSS like so is good:

```
import { Switch } from 'rc-switch'
import "rc-switch/dist/switch.css"
```

This will let people use it easily!

**Comment by benjycui** [comment]
https://unpkg.com/rc-switch@1.6.0/assets/index.css

**Comment by JikkuJose** [comment]
Isn't it better to depend on the installed package rather than having to link styles from outside. I had to extract the CSS and add it in to avoid this route.

**Comment by benjycui** [comment]
> https://unpkg.com/rc-switch@1.6.0/assets/index.css

This means that you can `import 'rc-switch/assets/index.css'`

**Comment by JikkuJose** [comment]
Oh cool, didn't know that!
