### ISSUE TITLE
源码中：当constructor和toggle声明了同一个变量名（checked），babel转译会有问题

### ISSUE THREAD

**Issue by kejiacheng** [react-component/switch#21]
当变量不一致时，babel转译后会将绑定了this的方法放进构造函数当中。但是现在因为变量一致并没有放进构造函数当中，使得focus和blur无法获取（如若focus和blur绑定了this）
不知道是不是babel转译时发生的问题。自己也尝试去看了babel源码，不过由于个人水平问题，实在没有找到具体的原因。

**Comment by kejiacheng** [comment]
```
let checked = false;
    if ('checked' in props) {
      checked = !!props.checked;
    } else {
      checked = !!props.defaultChecked;
    }
    this.state = { checked };
```

改为

```
let isChecked = false;
    if ('checked' in props) {
      isChecked = !!props.checked;
    } else {
      isChecked = !!props.defaultChecked;
    }
    this.state = { checked: isChecked };
```

然后babel转译看下结果

**Comment by yesmeck** [comment]
不同方法里的局部变量名不会相互影响的。

**Comment by kejiacheng** [comment]
你用babal转译一下就能看见不同了 我估计是babel转译的问题。所以你们这个switch就跟着有问题了

**Comment by yesmeck** [comment]
https://unpkg.com/rc-switch@1.6.0/lib/Switch.js

这个就是  babel 转换出来的。

**Comment by yesmeck** [comment]
建议你自己排查下。

**Comment by kejiacheng** [comment]
对的，你变量名变一下，就有区别了

**Comment by kejiacheng** [comment]
http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkifAL5wBmURcA5FKhowNwBQokscACvTAAVAJ5gkAZ1r0QTMEIC0McVI6c0pSfDQAbFJMkA5FCClwAvHBYBHAK7AWACkZ6DkkqbUBKLpxp2JBjApHAkEBBgTt64nJScGvqGcADKAO7AMGgAFnBIAB4w5AAm0oTEZBSxcHCaJNpQdhjQTgqRkjE4nDU1knYSUK1CHX49cLpI8MCS-NlIaADWSMWWtCi6kkhcY8A0cC4580vFjHDAJHBtYB3VY2czc4vLqwCEL1eSAHSHT8XbPdQkBskLcdg8js8rG8Pp9ikgaCg7LoYLMIX9ugCMTUYNlpp9tCgiqs8D9jgAue6o35wSj_eIYzQVcgwAAiwGKAFkIIEYNFQbUtPA8IiYBAAGIQNB2STYYrTFAAIwmK2oVhxeI-_xqu32IvFkulcAAZEa4C85ZJFcrOlieuqvjQDZJolqaRj6TVGZBKjAAOrAXS6ZBoJDAABuSEE7ScZEKUeuNp2ewOj2Op3OYQKMHjNy6dzg9vxkxSMEJSCcefztVTywpb1j2eG3xrxUwtpqlF8tviHYSvUmVOOTlJy0TPR1TkLMItVtH_JqLBgdigJFdPfHyZeKbR6YuU-G3jHY0LmxgJbLFfbPRHravnbXtv37U-pFmKBIAHNyzeu72MaKPw_CZVj5CwAD5-TqbRcDgV9dGARYaVWJ9rldKCdBbV4T1LIpmzRV0TwHFthxbX8ejghCFhItEyI9OBsnfYoJgAaSQUQWQgNILisJwkBicD-QnJBPiWURCDhSwLCsABmAB2To4AAekUuAABl4RgK9CJRYiEWBMiOzyYEzmTYTRPEkEpJkgBOBTlMQYAP2yTT820wdlknRo-LXIzNhM_YzLYizJJkgAmOAAB8IryESgogCSrLgABGaS7JUlIwHQJBsAAUQoJAoC03EvgAoDywMt0_xqeyAAlGOAvVaCdOA0jmC49EouBJAyLJcgzWZZCQDEGJIJikC5aUkAAVTAEC-MsCDK21ZNC3COEjztYrPjW4SlWXF1u1tCcUK-UgJs2GaNuxLaYTO7kLqibzDqqpqpWdDbVvi4THTeg6Xr2wYPq2nbPgBv63QxS0IyML6QJ2_jFsfYHYasHa6T7awSgKvkloFeohVqJJjC8bAFHhYB8nwDZZXlJVljbfMb1mANihYEhsFLBUAElRoKbBAnc4pmd0VnyGwT4JZYbQcyQtUbuGNDBWrNFkK2glcJvRX8a6nqcmERUebhfJVhnOmVgAfjgRQkrgClJwN3njaiuAAAYKvQnXMhyKn3BMMxVjcQw_akS98wAbUD4mzAAXTrF5I-Dhm7jDsmaApqnJFjgsvKTsYw4AAwAEhwVP042ShFBvfOs5vXOegL4vS8p8vFFN5Vq4pNv6e7CrF2XC4nCvAAeSRMpIK8ahwCXPilxt2nXRmieDiwcG6r3sh9oOvAXu5OcNgoV7X3r9e5x2d7GFgaBXk8UGhr7z_IkhWPYziSGvraRrG5-OK4h-agoxY788SlQmH_WCJBzrTTAEAr4n8JiQJmg_MCE84AjzHoTX2XgV5FxLpfMukgK7nDIFAfOlBkFVh6DgG8cBLZM1xCLNmts4ACxbMLUWJAwFD0UqPd85C7hcJ4SQPhNRaJxASOkdenwrhiAkNIKwlYE5eApPGGRUh8QwCgOcD8Scm4Z2UUIVRXwGhaKTl3Yo-jIiGNBhEXQSc6EszZhYkQqgvjvlEEnFhaI2GOIEAYlxnw3FJ1fCNL8TirEBCCEEiB90oFhP8REtAUSqaUTibIz4CSk570dqktRJA7AgAVAVOxLYclfAVDY0x8JETIkFqU6xEBbEYj1BKN6dTykNLbLScRutsiwiqUiOe1xiQYl0RsCkzA0CKCPjkRgxSvH0PYRSPJgYPEkEFt48gSykSNM9EvJRTBZkYjhAiAZtS1jAiSSEpASyIhgCSfBRYNzIidL8AUXg8BjnVPgBI3q7AgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=

**Comment by kejiacheng** [comment]
你可以看一下我只是改了constructor里面的变量名， 转译后会完全不同
