### ISSUE TITLE
Consider improving accessibility support with aria-role

### ISSUE THREAD

**Issue by AoDev** [react-component/switch#22]
Adding an `aria role` would improve accessibility of this component.

I think the best fit for this component would be to add the `switch role` per the [Mozilla guidelines here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_switch_role).

The gist of it would be to add:
* `role="switch"`
* `aria-checked={checked}`

on the outer span.

*In render method:*
```jsx
...
const checked = this.state.checked;
...
<span
  {...restProps}
  role="switch"
  aria-checked={checked}
  className={switchClassName}
  tabIndex={switchTabIndex}
  ref={this.saveNode}
  onKeyDown={this.handleKeyDown}
  onClick={this.toggle}
  onMouseUp={this.handleMouseUp}
>
  <span className={`${prefixCls}-inner`}>
    {checked ? checkedChildren : unCheckedChildren}
  </span>
</span>
```

**Comment by saitonakamura** [comment]
Also it's a good idea to use `button` instead of `span` cause button includes a lot of a11y stuff out of the box, like tab index, reacting to space and enter etc. so you can save some codelines

**Comment by saitonakamura** [comment]
Heydon Pickering has a really good blog about a11y btw https://inclusive-components.design/toggle-button/#theswitchrole

**Comment by zombieJ** [comment]
Welcome PR for this : )
