### ISSUE TITLE
Unknown Characters

### ISSUE THREAD

**Issue by polarathene** [react-component/switch#3]
Viewing from Chrome on Linux, seems I am missing font for two glyphs on the demo, one is `开`. Maybe is meant to be on/off with a glyph icon? Or is language character like chinese? For me all I can see is a square representing missing support.

**Comment by afc163** [comment]
It is a Chinese Character means `on`, and there is another Character `关` means `off`.

**Comment by polarathene** [comment]
Ok, that makes sense. Perhaps can use webfont to prevent seeing squares for those without chinese fonts installed :) Or use symbols like this switch: http://instructure-react.github.io/react-toggle/
