### ISSUE TITLE
[RFC] 用 ts 重写？

### ISSUE THREAD

**Issue by DiamondYuan** [react-component/switch#38]
我用 ts 重写一遍？

**Comment by afc163** [comment]
试试迁移到 https://umijs.github.io/umi-plugin-library/

**Comment by zombieJ** [comment]
> 试试迁移到 https://umijs.github.io/umi-plugin-library/

统一一下，如果 `umi-library` 可以的话，我们 rc-tools 的 ts 就先停一停。免得分裂了。

cc @chenshuai2144 @ycjcl868

**Comment by DiamondYuan** [comment]
> 试试迁移到 https://umijs.github.io/umi-plugin-library/

用 ts 重写，然后用 umi-library  么？

**Comment by afc163** [comment]
是时候统一了，维护两套意义不大，用 umi-library 吧。

**Comment by zombieJ** [comment]
第一个试点项目~
cc @clock157 @sorrycc

**Comment by chenshuai2144** [comment]
umi-library 是 mdx，改动很大

**Comment by zombieJ** [comment]
> umi-library 是 mdx，改动很大

看看可不可以搞个桥接模式，减少迁移成本？ @clock157

**Comment by DiamondYuan** [comment]
把根据代码生成接口文档也集成一下？这样文档就可以少些一点。

**Comment by DiamondYuan** [comment]
eslint 规范也是必须的。而且必须要单独配置 ts的 lint 规则。
有些 js 的规则和 ts 的规则冲突。

**Comment by DiamondYuan** [comment]
https://github.com/umijs/umi/issues/2147

**Comment by afc163** [comment]
这个库的配置还有一些不完美的地方，可以参照 https://github.com/react-component/footer 改一波。
